title: Puddles 101
description: Jump in.
template:
  repo: puddles-101-template
  name: puddles-101
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
